In [1]:
import numpy as np

In [2]:
np.array([2, 3, 4]) 

array([2, 3, 4])

In [3]:
np.array([[2, 3], [7,8],[8,9]])

array([[2, 3],
       [7, 8],
       [8, 9]])

In [4]:
from scipy import sparse

In [5]:
sparse.csr_matrix([[1, 2, 0], [0, 0, 3], [4, 0, 5]])

<3x3 sparse matrix of type '<class 'numpy.longlong'>'
	with 5 stored elements in Compressed Sparse Row format>

In [6]:
e = np.eye(4)
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
c = sparse.csr_matrix(e)
c

<4x4 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [8]:
# csr: Compressed Sparse Row format

In [11]:
dir(c)

['__abs__',
 '__add__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__idiv__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__pow__',
 '__radd__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmatmul__',
 '__rmul__',
 '__round__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '_add_dense',
 '_add_sparse',
 '_arg_min_or_max',
 '_arg_min_or_max_axis',
 '_asindices',
 '_binopt',
 '_cs_matrix__get_has_canonical_format',
 '_cs_matrix__get_sorted',
 '_cs_matrix__set_has_canonical_format',
 '_cs_matr

In [12]:
# dir() is a function which takes an object as input and gives all the attributes of the object 

In [13]:
c.toarray

<bound method _cs_matrix.toarray of <4x4 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Row format>>

In [15]:
vars(c)

{'_shape': (4, 4),
 'maxprint': 50,
 'data': array([1., 1., 1., 1.]),
 'indices': array([0, 1, 2, 3], dtype=int32),
 'indptr': array([0, 1, 2, 3, 4], dtype=int32)}

In [17]:
cs = sparse.csr_matrix(np.array([[1, 0, 0, 1, 0, 0], [0, 0, 2, 0, 0, 1], [0, 0, 0, 2, 0, 0]]))

In [18]:
vars(cs)

{'_shape': (3, 6),
 'maxprint': 50,
 'data': array([1, 1, 2, 1, 2], dtype=int64),
 'indices': array([0, 3, 2, 5, 3], dtype=int32),
 'indptr': array([0, 2, 4, 5], dtype=int32)}

In [24]:
np.linspace(2, 7, 4)

array([2.        , 3.66666667, 5.33333333, 7.        ])

In [25]:
print(cs)

  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2


In [26]:
print(c)

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [27]:
help(c)

Help on csr_matrix in module scipy.sparse.csr object:

class csr_matrix(scipy.sparse.compressed._cs_matrix)
 |  Compressed Sparse Row matrix
 |  
 |  This can be instantiated in several ways:
 |      csr_matrix(D)
 |          with a dense matrix or rank-2 ndarray D
 |  
 |      csr_matrix(S)
 |          with another sparse matrix S (equivalent to S.tocsr())
 |  
 |      csr_matrix((M, N), [dtype])
 |          to construct an empty matrix with shape (M, N)
 |          dtype is optional, defaulting to dtype='d'.
 |  
 |      csr_matrix((data, (row_ind, col_ind)), [shape=(M, N)])
 |          where ``data``, ``row_ind`` and ``col_ind`` satisfy the
 |          relationship ``a[row_ind[k], col_ind[k]] = data[k]``.
 |  
 |      csr_matrix((data, indices, indptr), [shape=(M, N)])
 |          is the standard CSR representation where the column indices for
 |          row i are stored in ``indices[indptr[i]:indptr[i+1]]`` and their
 |          corresponding values are stored in ``data[indptr[i]:

In [28]:
# To get detailed information about an object of a class, use the help() function
# To get info about a particular method you are writing, while typing press shift + tab

In [29]:
np.arange(4)

array([0, 1, 2, 3])

In [30]:
np.ones(4)

array([1., 1., 1., 1.])

In [39]:
data = np.ones(4)
data[2] = 5
data

array([1., 1., 5., 1.])

In [32]:
row_indices = np.arange(4)

In [33]:
col_indices = np.arange(4)

In [40]:
coo = sparse.coo_matrix((data, (row_indices, col_indices)))
coo

<4x4 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in COOrdinate format>

In [41]:
print(coo)

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	5.0
  (3, 3)	1.0


In [ ]:
# coo_matrix ( coordinated matrix is used to construct a sparse matrix whi)